In [11]:
import pandas as pd 
import numpy as np 
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',10)

In [12]:
import os
print(os.getcwd())
# checking directory

c:\Users\hitin\Downloads\Mutual_Fund_Analytics_Project\Notebooks

In [13]:
nav_df = pd.read_csv("../Data/Raw/02_nav_history.csv")
nav_df.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [14]:
nav_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  object
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ MB

In [15]:
print(nav_df.columns.to_list())
print(nav_df.shape)

['amfi_code', 'date', 'nav']
(46000, 3)

In [16]:
nav_df['date']= pd.to_datetime(nav_df['date'],errors='coerce')
# converts date column to datetime format, errors='coerce' will convert invalid parsing (date) to NaT

In [17]:
nav_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  datetime64[ns]
 2   nav        46000 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 1.1 MB

In [21]:
nav_df= nav_df.sort_values(by=['amfi_code','date']).reset_index(drop=True)
nav_df.head()

   amfi_code       date       nav
0     100016 2022-01-03  520.4608
1     100016 2022-01-04  515.0971
2     100016 2022-01-05  521.7239
3     100016 2022-01-06  515.7880
4     100016 2022-01-07  515.1639

In [22]:
nav_df.isna().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [23]:
nav_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  datetime64[ns]
 2   nav        46000 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 1.1 MB

In [25]:
nav_df["nav"].isnull().sum()

np.int64(0)

In [26]:
nav_df[nav_df["nav"].isnull()]

Empty DataFrame
Columns: [amfi_code, date, nav]
Index: []

In [27]:
# checking for duplicate rows in the dataframe
duplicate_count = nav_df.duplicated().sum()
print(f"Duplicate rows: {duplicate_count}")

Duplicate rows: 0

In [28]:
nav_df = nav_df[nav_df["nav"] > 0].reset_index(drop=True)

In [30]:
# checking processed dataframe information
print(nav_df.info())
print(nav_df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  datetime64[ns]
 2   nav        46000 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 1.1 MB
None
           amfi_code                           date           nav
count   46000.000000                          46000  46000.000000
mean   120247.000000  2024-03-16 12:00:00.000000256    269.570265
min    100016.000000            2022-01-03 00:00:00     26.136600
25%    118632.750000            2023-02-08 00:00:00     69.170425
50%    119551.500000            2024-03-16 12:00:00    122.732150
75%    120842.250000            2025-04-23 00:00:00    260.338675
max    149324.000000            2026-05-29 00:00:00   4268.549700
std     14352.317221                            NaN    577.187060

In [31]:
# saving the cleaned dataframe to a new CSV file
nav_df.to_csv("../Data/Processed/02_nav_history_cleaned.csv",index=False)